# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabrizio/inrim/gscv/conductor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabrizio/inrim/gscv/conductor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabrizio/inrim/gscv/conductor/CMakeFiles /home/fabrizio/inrim/gscv/conductor//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabrizio/inrim/gscv/conductor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named conductor

# Build rule for target.
conductor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 conductor
.PHONY : conductor

# fast build rule for target.
conductor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conductor.dir/build.make CMakeFiles/conductor.dir/build
.PHONY : conductor/fast

#=============================================================================
# Target rules for targets named example_single_python_task

# Build rule for target.
example_single_python_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_single_python_task
.PHONY : example_single_python_task

# fast build rule for target.
example_single_python_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_single_python_task.dir/build.make CMakeFiles/example_single_python_task.dir/build
.PHONY : example_single_python_task/fast

#=============================================================================
# Target rules for targets named example_multiple_task

# Build rule for target.
example_multiple_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_multiple_task
.PHONY : example_multiple_task

# fast build rule for target.
example_multiple_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_multiple_task.dir/build.make CMakeFiles/example_multiple_task.dir/build
.PHONY : example_multiple_task/fast

#=============================================================================
# Target rules for targets named example_multi_pool_concurrent

# Build rule for target.
example_multi_pool_concurrent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_multi_pool_concurrent
.PHONY : example_multi_pool_concurrent

# fast build rule for target.
example_multi_pool_concurrent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_multi_pool_concurrent.dir/build.make CMakeFiles/example_multi_pool_concurrent.dir/build
.PHONY : example_multi_pool_concurrent/fast

#=============================================================================
# Target rules for targets named example_one_shot_abs_time

# Build rule for target.
example_one_shot_abs_time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_one_shot_abs_time
.PHONY : example_one_shot_abs_time

# fast build rule for target.
example_one_shot_abs_time/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_one_shot_abs_time.dir/build.make CMakeFiles/example_one_shot_abs_time.dir/build
.PHONY : example_one_shot_abs_time/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named run_example_single_python_task

# Build rule for target.
run_example_single_python_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_single_python_task
.PHONY : run_example_single_python_task

# fast build rule for target.
run_example_single_python_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_single_python_task.dir/build.make CMakeFiles/run_example_single_python_task.dir/build
.PHONY : run_example_single_python_task/fast

#=============================================================================
# Target rules for targets named run_example_multiple_task

# Build rule for target.
run_example_multiple_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_multiple_task
.PHONY : run_example_multiple_task

# fast build rule for target.
run_example_multiple_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_multiple_task.dir/build.make CMakeFiles/run_example_multiple_task.dir/build
.PHONY : run_example_multiple_task/fast

#=============================================================================
# Target rules for targets named run_example_multi_pool_concurrent

# Build rule for target.
run_example_multi_pool_concurrent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_multi_pool_concurrent
.PHONY : run_example_multi_pool_concurrent

# fast build rule for target.
run_example_multi_pool_concurrent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_multi_pool_concurrent.dir/build.make CMakeFiles/run_example_multi_pool_concurrent.dir/build
.PHONY : run_example_multi_pool_concurrent/fast

#=============================================================================
# Target rules for targets named run_examples

# Build rule for target.
run_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_examples
.PHONY : run_examples

# fast build rule for target.
run_examples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_examples.dir/build.make CMakeFiles/run_examples.dir/build
.PHONY : run_examples/fast

#=============================================================================
# Target rules for targets named run_regression_tests

# Build rule for target.
run_regression_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_regression_tests
.PHONY : run_regression_tests

# fast build rule for target.
run_regression_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_regression_tests.dir/build.make CMakeFiles/run_regression_tests.dir/build
.PHONY : run_regression_tests/fast

src/conductor.o: src/conductor.cpp.o
.PHONY : src/conductor.o

# target to build an object file
src/conductor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conductor.dir/build.make CMakeFiles/conductor.dir/src/conductor.cpp.o
.PHONY : src/conductor.cpp.o

src/conductor.i: src/conductor.cpp.i
.PHONY : src/conductor.i

# target to preprocess a source file
src/conductor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conductor.dir/build.make CMakeFiles/conductor.dir/src/conductor.cpp.i
.PHONY : src/conductor.cpp.i

src/conductor.s: src/conductor.cpp.s
.PHONY : src/conductor.s

# target to generate assembly for a file
src/conductor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/conductor.dir/build.make CMakeFiles/conductor.dir/src/conductor.cpp.s
.PHONY : src/conductor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... example_multi_pool_concurrent"
	@echo "... example_multiple_task"
	@echo "... example_one_shot_abs_time"
	@echo "... example_single_python_task"
	@echo "... examples"
	@echo "... run_example_multi_pool_concurrent"
	@echo "... run_example_multiple_task"
	@echo "... run_example_single_python_task"
	@echo "... run_examples"
	@echo "... run_regression_tests"
	@echo "... conductor"
	@echo "... src/conductor.o"
	@echo "... src/conductor.i"
	@echo "... src/conductor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

