# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabrizio/inrim/gscv/cppscheduler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabrizio/inrim/gscv/cppscheduler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabrizio/inrim/gscv/cppscheduler/CMakeFiles /home/fabrizio/inrim/gscv/cppscheduler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabrizio/inrim/gscv/cppscheduler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cppscheduler

# Build rule for target.
cppscheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppscheduler
.PHONY : cppscheduler

# fast build rule for target.
cppscheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/build
.PHONY : cppscheduler/fast

#=============================================================================
# Target rules for targets named example_single_cpp_task

# Build rule for target.
example_single_cpp_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_single_cpp_task
.PHONY : example_single_cpp_task

# fast build rule for target.
example_single_cpp_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_single_cpp_task.dir/build.make CMakeFiles/example_single_cpp_task.dir/build
.PHONY : example_single_cpp_task/fast

#=============================================================================
# Target rules for targets named example_single_python_task

# Build rule for target.
example_single_python_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_single_python_task
.PHONY : example_single_python_task

# fast build rule for target.
example_single_python_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_single_python_task.dir/build.make CMakeFiles/example_single_python_task.dir/build
.PHONY : example_single_python_task/fast

#=============================================================================
# Target rules for targets named example_multiple_task

# Build rule for target.
example_multiple_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_multiple_task
.PHONY : example_multiple_task

# fast build rule for target.
example_multiple_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_multiple_task.dir/build.make CMakeFiles/example_multiple_task.dir/build
.PHONY : example_multiple_task/fast

#=============================================================================
# Target rules for targets named example_multi_pool_concurrent

# Build rule for target.
example_multi_pool_concurrent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_multi_pool_concurrent
.PHONY : example_multi_pool_concurrent

# fast build rule for target.
example_multi_pool_concurrent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_multi_pool_concurrent.dir/build.make CMakeFiles/example_multi_pool_concurrent.dir/build
.PHONY : example_multi_pool_concurrent/fast

#=============================================================================
# Target rules for targets named example_one_shot_abs_time

# Build rule for target.
example_one_shot_abs_time: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_one_shot_abs_time
.PHONY : example_one_shot_abs_time

# fast build rule for target.
example_one_shot_abs_time/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_one_shot_abs_time.dir/build.make CMakeFiles/example_one_shot_abs_time.dir/build
.PHONY : example_one_shot_abs_time/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/examples.dir/build.make CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named run_example_single_cpp_task

# Build rule for target.
run_example_single_cpp_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_single_cpp_task
.PHONY : run_example_single_cpp_task

# fast build rule for target.
run_example_single_cpp_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_single_cpp_task.dir/build.make CMakeFiles/run_example_single_cpp_task.dir/build
.PHONY : run_example_single_cpp_task/fast

#=============================================================================
# Target rules for targets named run_example_single_python_task

# Build rule for target.
run_example_single_python_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_single_python_task
.PHONY : run_example_single_python_task

# fast build rule for target.
run_example_single_python_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_single_python_task.dir/build.make CMakeFiles/run_example_single_python_task.dir/build
.PHONY : run_example_single_python_task/fast

#=============================================================================
# Target rules for targets named run_example_multiple_task

# Build rule for target.
run_example_multiple_task: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_multiple_task
.PHONY : run_example_multiple_task

# fast build rule for target.
run_example_multiple_task/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_multiple_task.dir/build.make CMakeFiles/run_example_multiple_task.dir/build
.PHONY : run_example_multiple_task/fast

#=============================================================================
# Target rules for targets named run_example_multi_pool_concurrent

# Build rule for target.
run_example_multi_pool_concurrent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_example_multi_pool_concurrent
.PHONY : run_example_multi_pool_concurrent

# fast build rule for target.
run_example_multi_pool_concurrent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_example_multi_pool_concurrent.dir/build.make CMakeFiles/run_example_multi_pool_concurrent.dir/build
.PHONY : run_example_multi_pool_concurrent/fast

#=============================================================================
# Target rules for targets named run_examples

# Build rule for target.
run_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_examples
.PHONY : run_examples

# fast build rule for target.
run_examples/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_examples.dir/build.make CMakeFiles/run_examples.dir/build
.PHONY : run_examples/fast

#=============================================================================
# Target rules for targets named run_regression_tests

# Build rule for target.
run_regression_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_regression_tests
.PHONY : run_regression_tests

# fast build rule for target.
run_regression_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_regression_tests.dir/build.make CMakeFiles/run_regression_tests.dir/build
.PHONY : run_regression_tests/fast

custom_tasks/user_cpp_task_math.o: custom_tasks/user_cpp_task_math.cpp.o
.PHONY : custom_tasks/user_cpp_task_math.o

# target to build an object file
custom_tasks/user_cpp_task_math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_math.cpp.o
.PHONY : custom_tasks/user_cpp_task_math.cpp.o

custom_tasks/user_cpp_task_math.i: custom_tasks/user_cpp_task_math.cpp.i
.PHONY : custom_tasks/user_cpp_task_math.i

# target to preprocess a source file
custom_tasks/user_cpp_task_math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_math.cpp.i
.PHONY : custom_tasks/user_cpp_task_math.cpp.i

custom_tasks/user_cpp_task_math.s: custom_tasks/user_cpp_task_math.cpp.s
.PHONY : custom_tasks/user_cpp_task_math.s

# target to generate assembly for a file
custom_tasks/user_cpp_task_math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_math.cpp.s
.PHONY : custom_tasks/user_cpp_task_math.cpp.s

custom_tasks/user_cpp_task_print.o: custom_tasks/user_cpp_task_print.cpp.o
.PHONY : custom_tasks/user_cpp_task_print.o

# target to build an object file
custom_tasks/user_cpp_task_print.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_print.cpp.o
.PHONY : custom_tasks/user_cpp_task_print.cpp.o

custom_tasks/user_cpp_task_print.i: custom_tasks/user_cpp_task_print.cpp.i
.PHONY : custom_tasks/user_cpp_task_print.i

# target to preprocess a source file
custom_tasks/user_cpp_task_print.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_print.cpp.i
.PHONY : custom_tasks/user_cpp_task_print.cpp.i

custom_tasks/user_cpp_task_print.s: custom_tasks/user_cpp_task_print.cpp.s
.PHONY : custom_tasks/user_cpp_task_print.s

# target to generate assembly for a file
custom_tasks/user_cpp_task_print.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_print.cpp.s
.PHONY : custom_tasks/user_cpp_task_print.cpp.s

custom_tasks/user_cpp_task_state.o: custom_tasks/user_cpp_task_state.cpp.o
.PHONY : custom_tasks/user_cpp_task_state.o

# target to build an object file
custom_tasks/user_cpp_task_state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_state.cpp.o
.PHONY : custom_tasks/user_cpp_task_state.cpp.o

custom_tasks/user_cpp_task_state.i: custom_tasks/user_cpp_task_state.cpp.i
.PHONY : custom_tasks/user_cpp_task_state.i

# target to preprocess a source file
custom_tasks/user_cpp_task_state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_state.cpp.i
.PHONY : custom_tasks/user_cpp_task_state.cpp.i

custom_tasks/user_cpp_task_state.s: custom_tasks/user_cpp_task_state.cpp.s
.PHONY : custom_tasks/user_cpp_task_state.s

# target to generate assembly for a file
custom_tasks/user_cpp_task_state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_task_state.cpp.s
.PHONY : custom_tasks/user_cpp_task_state.cpp.s

custom_tasks/user_cpp_tasks.o: custom_tasks/user_cpp_tasks.cpp.o
.PHONY : custom_tasks/user_cpp_tasks.o

# target to build an object file
custom_tasks/user_cpp_tasks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_tasks.cpp.o
.PHONY : custom_tasks/user_cpp_tasks.cpp.o

custom_tasks/user_cpp_tasks.i: custom_tasks/user_cpp_tasks.cpp.i
.PHONY : custom_tasks/user_cpp_tasks.i

# target to preprocess a source file
custom_tasks/user_cpp_tasks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_tasks.cpp.i
.PHONY : custom_tasks/user_cpp_tasks.cpp.i

custom_tasks/user_cpp_tasks.s: custom_tasks/user_cpp_tasks.cpp.s
.PHONY : custom_tasks/user_cpp_tasks.s

# target to generate assembly for a file
custom_tasks/user_cpp_tasks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/custom_tasks/user_cpp_tasks.cpp.s
.PHONY : custom_tasks/user_cpp_tasks.cpp.s

src/cppscheduler.o: src/cppscheduler.cpp.o
.PHONY : src/cppscheduler.o

# target to build an object file
src/cppscheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/src/cppscheduler.cpp.o
.PHONY : src/cppscheduler.cpp.o

src/cppscheduler.i: src/cppscheduler.cpp.i
.PHONY : src/cppscheduler.i

# target to preprocess a source file
src/cppscheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/src/cppscheduler.cpp.i
.PHONY : src/cppscheduler.cpp.i

src/cppscheduler.s: src/cppscheduler.cpp.s
.PHONY : src/cppscheduler.s

# target to generate assembly for a file
src/cppscheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cppscheduler.dir/build.make CMakeFiles/cppscheduler.dir/src/cppscheduler.cpp.s
.PHONY : src/cppscheduler.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example_multi_pool_concurrent"
	@echo "... example_multiple_task"
	@echo "... example_one_shot_abs_time"
	@echo "... example_single_cpp_task"
	@echo "... example_single_python_task"
	@echo "... examples"
	@echo "... run_example_multi_pool_concurrent"
	@echo "... run_example_multiple_task"
	@echo "... run_example_single_cpp_task"
	@echo "... run_example_single_python_task"
	@echo "... run_examples"
	@echo "... run_regression_tests"
	@echo "... cppscheduler"
	@echo "... custom_tasks/user_cpp_task_math.o"
	@echo "... custom_tasks/user_cpp_task_math.i"
	@echo "... custom_tasks/user_cpp_task_math.s"
	@echo "... custom_tasks/user_cpp_task_print.o"
	@echo "... custom_tasks/user_cpp_task_print.i"
	@echo "... custom_tasks/user_cpp_task_print.s"
	@echo "... custom_tasks/user_cpp_task_state.o"
	@echo "... custom_tasks/user_cpp_task_state.i"
	@echo "... custom_tasks/user_cpp_task_state.s"
	@echo "... custom_tasks/user_cpp_tasks.o"
	@echo "... custom_tasks/user_cpp_tasks.i"
	@echo "... custom_tasks/user_cpp_tasks.s"
	@echo "... src/cppscheduler.o"
	@echo "... src/cppscheduler.i"
	@echo "... src/cppscheduler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

